### ISSUE TITLE
MIN_STAKE_AMOUNT appears to be unused in the rest of the code

### ISSUE THREAD

**Issue by 4thehex** [wise-foundation/wise-token-contracts#10]
Maybe this was meant to be used as a minimum amount of YODAs for new stakes?  I could see the reason for this, to prevent spam transactions, or maybe other mathematical reasons?

https://github.com/wise-foundation/wise-token-contracts/blob/b06df7cb816f9b123ca9c8a6db19f94df249681c/contracts/Declaration.sol#L109

**Comment by 4thehex** [comment]
Oops, sorry...  Accidental button click

**Comment by vm06007** [comment]
addressed, thanks for reporting, we decided to use it after a fud about axion allowing to open 0 token stakes, technically this is still fine since they generate 0 shares, but also if the amount is too low (like 1 YODA) it is impossible to penalize such stakes (unless just taking full YODA away) in any case adding use for this is planned, will include in next commit. Please leave your Ethereum address

**Comment by 4thehex** [comment]
Cool, thanks for replying!

`0x5148E04B2E7A3A5f69304cebC3Be6ba6278E3923`

**Comment by vm06007** [comment]
sent: https://etherscan.io/tx/0x67b140dc300977f30c4f1e668e5b8fc5bad38ba1ff09539384b0321ae50154a1
