### ISSUE TITLE
Unnecessary calculation in myRefundAmount

### ISSUE THREAD

**Issue by pauliax** [wise-foundation/wise-token-contracts#3]
https://github.com/wise-foundation/wise-token-contracts/blob/b06df7cb816f9b123ca9c8a6db19f94df249681c/contracts/RefundSponsor.sol#L107-L121

The first function (with no parameters) returns the result from the second function but also does the same multiplication and division. I think that was not intended and it just had to return getRefundAmount(msg.sender).

**Comment by vm06007** [comment]
since myRefundAmount() is just an external view it does not affect state of contract, displaying data on UI we can use getRefundAmount(), this is also not the scope of bounty as more focus should be put to staking contract, but thanks for pointing it out. However, don't think we need to redeploy as gasRefund already used for LT contract. Just to be aware not to use myRefundAmount() on UI, instead we can use getRefundAmount(address x).

**Comment by pauliax** [comment]
Yep, this only affects the frontend (and users that may try to read values on EtherScan).

**Comment by vm06007** [comment]
I'm not sure about EtherScan, last time I've checked it would return 0 (I guess that could be confusing) even if I'm connected with the wallet and triggering the above function that returns actual value, also I'm thinking to put payoutPercent to 100% to make it more fair (this also then solves this issue) since original gas recorded by contract is always a bit smaller than actual gas spent by transaction. I can see there's a discrepancy because it also needs gas to interact with gasRefunder and this cannot be tracked, e.g. (last state writing action) 

![Screen Shot 2020-11-19 at 2 37 48 AM](https://user-images.githubusercontent.com/1138692/99579017-390e1680-2a10-11eb-94d8-6a3d3b956d95.jpg)

guess I'll leave a comment on EtherScan for that contract for users to use `getRefundAmount(x)` if they are confused or would like to check amount they can withdraw. Thanks for pointing it out!

**Comment by vm06007** [comment]
addressing issue: https://github.com/wise-foundation/wise-token/compare/099d488ec250...42e4e17db9e4 
@pauliax you can close this thread and would you please leave your wallet address here in the comment before you do that.

**Comment by pauliax** [comment]
0x523B5b2Cc58A818667C22c862930B141f85d49DD

**Comment by vm06007** [comment]
sent: https://etherscan.io/tx/0x0ee9ce5293b12019763bf43ac4d84ed88564c8ec15646b5496565521663d333d
