### ISSUE TITLE
Function notContract does not forbid contracts in all cases

### ISSUE THREAD

**Issue by pauliax** [wise-foundation/wise-token-contracts#4]
https://github.com/wise-foundation/wise-token-contracts/blob/b06df7cb816f9b123ca9c8a6db19f94df249681c/contracts/Helper.sol#L11-L17

https://github.com/wise-foundation/wise-token-contracts/blob/b06df7cb816f9b123ca9c8a6db19f94df249681c/contracts/LiquidityTransformer.sol#L1200-L1206

This function is used to verify whether a call was made from an externally owned account (EOA) or a contract account. If an address contains code, it’s not an EOA but a contract account. However, a contract does not have source code available during construction. This means that while the constructor is running, it can make calls to other contracts, but extcodesize for its address returns zero. Below is a minimal example that shows how this check can be circumvented:

![image](https://user-images.githubusercontent.com/22328890/99572505-71483180-29dd-11eb-8154-88411d3dcb76.png)

**Comment by vm06007** [comment]
This was already mentioned also in audit report by CoinFabrik, we are aware this won't prevent 100% of contracts or contracts in their inception, but this would not allow them to run referrals pools (main purpose of combating this issue) while there's no 100% solution for this we could review other ways to prevent referral address to be a smart contract. Suggest something more effective? If you have a proposal for improvement please let us know. Main bottom line is that in a long run a contract won't be able to exploit this since a creation of the pool would require the same contract interacting with Wise contract in the long run through Interface or other function except constructor. Thanks for pointing this out though. Again, this is something CoinFabrik already brought up in audit.

**Comment by vm06007** [comment]
btw @pauliax do you think a scenario like this could be still possible? (not sure how expensive it would be or worthy to use) a parent smart-contract could create empty / fake child contracts as a one time use to execute createStake() with referral address (in this case these fake children contracts are the owners of the referral shares and need to execute referralInterest() function in order to get the rewards. I believe if we also check for smart-contract detection during referralInterest() it would prevent these fake / child contracts to execute that function since it would have to be outside of constructor

**Comment by pauliax** [comment]
An alternative approach is to check`(tx.origin == msg.sender)`, though this also not highly recommended: https://github.com/ConsenSys/smart-contract-best-practices/blob/master/docs/recommendations.md#avoid-using-txorigin

And yeah as you mentioned this scenario is very unlikely so this issue is just for letting you know that extcodesize = 0 is not always sufficient. 

https://stackoverflow.com/a/54056854/5551988

**Comment by vm06007** [comment]
Thanks @pauliax, we are aware :)

**Comment by pauliax** [comment]
This is the approach that Loopring uses in its new implementation:
https://github.com/Loopring/protocols/blob/47969503aab749c0b8a9ff2078a64b226f931ab7/packages/hebao_v1/contracts/lib/AddressUtil.sol#L13-L28

~~I am not sure if this is effective in all cases but maybe you will find it useful to consider in the future.~~
Edit: this approach is also vulnerable when invoking a code in the constructor.
