### ISSUE TITLE
ERC20 known vulnerability

### ISSUE THREAD

**Issue by A-S-K-3** [wise-foundation/wise-token-contracts#7]
Even though the contract is standard, it is vulnerable to double withdrawal attack. Hard to exploit, but not impossible.
Description and possible solution --> https://docs.google.com/document/d/1YLPtQxZu1UAvO9cZ1O2RPXBbT0mooh4DYKjA_jp-RLM
Telegram: @mrrobot3_3

**Comment by vm06007** [comment]
can we focus on actual staking instead of this? You can apply this concern to ANY ERC20 token, I think this is something you could propose for next request for comments standard. Thanks. Note, that in given LT staking cases we are using `safeTransfer` and `safeTransferFrom` and that should be the norm now when writing contracts on top of existing ERC20.
